--  Funtion LPE

SET NOCOUNT ON;

DECLARE @PromotionCode NVARCHAR(MAX) = ''                --ใส่เลข promotion มากกว่า 1 ให้ ใส่ ,  เช่น 12551,545454
DECLARE @ProductCode NVARCHAR(MAX) = ''                  --ใส่เลข Product มากกว่า 1 ให้ ใส่ ,  เช่น 12551,545454
DECLARE @LogicalOperator NVARCHAR(MAX) = 'OR'            --ใส่   OR   หรือ AND

-- Funtion SLIP
DECLARE @POS_NO INT = __POS_NO__
DECLARE @SlipNo INT = 0

-- Funtion ตรวจสอบค่าของ @PromotionCode และ @ProductCode เพื่อกำหนด WHERE
DECLARE @MMBR_ACCT_ID NVARCHAR(MAX) = '31022089';
DECLARE @Mstamp_3 NVARCHAR(7) = '3700062'; -- หมายเลขพรีเมียมพิเศษ
DECLARE @Mstamp_1 NVARCHAR(7) = '3700061'; -- หมายเลขพรีเมียมพิเศษ
DECLARE @PREMIUM_ID NVARCHAR(MAX) = '31021362,9104161,3700057, 9103523'; -- รายการพรีเมียมที่ขาใช้ในการค้นหา
DECLARE @PREMIUM_stamp NVARCHAR(MAX);
DECLARE @COMMON_TRN_NO VARCHAR(MAX);
DECLARE @FilterCondition NVARCHAR(MAX);




USE POSG2
IF OBJECT_ID('tempdb..#TempTable') IS NOT NULL
    DROP TABLE #TempTable;
CREATE TABLE #TempTable (RECEIPT_NO NVARCHAR(50),RULE_ID NVARCHAR(50),RULE_NAME NVARCHAR(MAX),PRINT_SEQ_NO INT,POS_NO INT,STORE_ID NVARCHAR(50),COMMON_TRN_NO NVARCHAR(50),PROMOTION_TYPE INT);
-- เพิ่มข้อมูลเข้า Temporary Table
INSERT INTO #TempTable (RECEIPT_NO,RULE_ID,RULE_NAME,PRINT_SEQ_NO,POS_NO, STORE_ID,COMMON_TRN_NO,PROMOTION_TYPE)
SELECT RECEIPT_NO,RULE_ID,RULE_NAME, PRINT_SEQ_NO,  POS_NO,STORE_ID,COMMON_TRN_NO,PROMOTION_TYPE
FROM TA_PROMOTION_HITRULE AS PROMOTION_HITRULE

WHERE POS_NO = @POS_NO and(
    @SlipNo = 0
		AND COMMON_TRN_NO in (
			SELECT MAX(COMMON_TRN_NO)
			FROM TA_PROMOTION_HITRULE
			WHERE POS_NO = @POS_NO and len(RECEIPT_NO)<7))
		OR (
    @SlipNo <> 0
			AND COMMON_TRN_NO in (
			SELECT MAX(COMMON_TRN_NO)
			FROM TA_PROMOTION_HITRULE
			WHERE POS_NO = @POS_NO AND RECEIPT_NO = @SlipNo and len(RECEIPT_NO)>7
			AND POS_NO = @POS_NO))

ORDER BY RUNNING_NO ;
--SELECT * FROM #TempTable;

SELECT @COMMON_TRN_NO = MAX(COMMON_TRN_NO) FROM #TempTable;

IF LEN(@PromotionCode) > 1 AND LEN(@ProductCode) > 1
BEGIN
    SET @ProductCode = '''' + REPLACE(@ProductCode, ',', ''', ''') + '''';
    SET @PromotionCode = '''' + REPLACE(@PromotionCode, ',', ''', ''') + '''';
    SET @FilterCondition = 'WHERE Entity.EntityId IN (' + @ProductCode + ') '
                            + @LogicalOperator + ' Header.MMBR_PROM_ID IN (' + @PromotionCode + ')';
END
ELSE IF LEN(@ProductCode) > 1
BEGIN
    SET @ProductCode = '''' + REPLACE(@ProductCode, ',', ''', ''') + '''';
    SET @FilterCondition = 'WHERE Entity.EntityId IN (' + @ProductCode + ')';
END
ELSE IF LEN(@PromotionCode) > 1
BEGIN
    SET @PromotionCode = '''' + REPLACE(@PromotionCode, ',', ''', ''') + '''';
    SET @FilterCondition = 'WHERE Header.MMBR_PROM_ID IN (' + @PromotionCode + ')';
END
ELSE IF LEN(@MMBR_ACCT_ID) > 1
BEGIN
    SET @FilterCondition = 'WHERE Header.MMBR_ACCT_ID IN (' + @MMBR_ACCT_ID + ')';
END

DECLARE @FromClause NVARCHAR(MAX) = '
    FROM
        [LPE_PROM].[dbo].[LPE_PromotionHeader] AS Header
    INNER JOIN
        [LPE_PROM].[dbo].[LPE_PromotionDistribution] AS Distribution
        ON Header.MMBR_PROM_ID = Distribution.MMBR_PROM_ID
    LEFT JOIN
        [LPE_PROM].[dbo].[LPE_PromotionAccounts] AS Accounts
        ON (Header.RWRD_MMBR_ACCOUNT = Accounts.MMBR_ACCT_ID AND Header.RWRD_MMBR_ACCOUNT IS NOT NULL)
        OR (Header.MMBR_ACCT_ID = Accounts.MMBR_ACCT_ID AND Header.RWRD_MMBR_ACCOUNT IS NOT NULL)
    LEFT JOIN
        [LPE_PROM].[dbo].[LPE_PromotionBucketEntity] AS Entity
         ON Header.MMBR_PROM_ID = Entity.MMBR_PROM_ID ';
DECLARE @GroupClause NVARCHAR(MAX) = '
    GROUP BY
        Distribution.StoreId,
        Header.MMBR_PROM_ID,
        Distribution.Suspended,
        Header.Suspended,
        Header.COUPON_ID,
        Header.MMBR_ACCT_ID ,
        Header.RWRD_MMBR_ACCOUNT,
        Header.RWRD_TYP,
        Header.LMT_QTY ,
        Header.PROM_DESC ,
        Header.STRT_DATE ,
        Header.END_DATE ,
        Accounts.DESCR,
        Entity.BucketId,
        Distribution.StartDate,
        Distribution.EndDate';
DECLARE @SqlCount NVARCHAR(MAX) =
    'SELECT
        COUNT(Entity.BucketId) AS ProductCount,
        Distribution.StoreId,
        Header.MMBR_PROM_ID AS PromotionId,
        Distribution.Suspended,
        Header.SUSPENDED AS Header_Suspended,
        Header.COUPON_ID AS CouponId,
        Header.MMBR_ACCT_ID AS AccountId,
        Header.RWRD_MMBR_ACCOUNT AS AccountReward,
        Header.RWRD_TYP AS RewardType,
        Header.LMT_QTY AS LimitQuantity,
        Header.STRT_DATE AS StartDate,
        CASE
            WHEN Header.STRT_DATE = Distribution.StartDate THEN NULL
            ELSE Distribution.StartDate
        END AS DistributionStartDate,
        Header.END_DATE AS EndDate,
        CASE
            WHEN Header.END_DATE = Distribution.EndDate THEN NULL
            ELSE Distribution.EndDate
        END AS DistributionEndDate,
        Entity.BucketId
    ' + @FromClause + @FilterCondition + @GroupClause + ';';
DECLARE @JoinClause NVARCHAR(MAX) = '
    LEFT JOIN
        MA_BARCODE AS Barcode
        ON Entity.EntityId COLLATE Thai_CI_AS = Barcode.PRODUCT_CODE COLLATE Thai_CI_AS
        OR (Entity.EntityId COLLATE Thai_CI_AS LIKE ''%'' + Barcode.PRODUCT_CODE'+ ' COLLATE Thai_CI_AS)

    LEFT JOIN
        MS_PRODUCT AS Product
        ON Entity.EntityId COLLATE Thai_CI_AS = Barcode.PRODUCT_CODE COLLATE Thai_CI_AS
    LEFT JOIN
        MS_PRICE_SALE AS Price
         ON Barcode.PRODUCT_CODE = Product.PRODUCT_CODE
    LEFT JOIN
        MS_PRODUCT_CONVERT AS CONVER
         ON Barcode.PRODUCT_CODE = CONVER.PRODUCT_SOURCE ';
DECLARE @SqlPromotion NVARCHAR(MAX) =
    'SELECT distinct Top 50
        Header.MMBR_PROM_ID AS PromotionId,
        CASE
            WHEN Entity.AttachmentMode = 0 THEN ''Available''
            WHEN Entity.AttachmentMode = 2 THEN ''Unavailable''
            ELSE ''Unknown''
        END AS AttachmentStatus,
        Entity.EntityId,
        Barcode.Barcode,
        CONVER.QTY_SOURCE AS qty ,
        CONVER.UNIT_TYPE_SOURCE AS Classifier ,
        CONVER.PRODUCT_TARGET AS productmap ,
        CONVER.QTY_TARGET AS qtys ,
        CONVER.UNIT_TYPE_TARGET AS Classifiers ' + @FromClause + @JoinClause + @FilterCondition;
DECLARE @ITEM NVARCHAR(MAX) ='SELECT CAST(ts.RECEIPT_NO AS CHAR)AS RECEIPT,
		CAST(ts.POS_NO AS CHAR)AS POS ,
		CAST(COUNT(ts.RECEIPT_NO) AS CHAR) AS PRODUCT_CODE ,
		'''' AS PRODUCT_NAME
		,'''' AS PRICE ,
		 '''' AS QTY,
		 sum(ts.SUB_TOTAL_AMT) AS TOTAL_AMT,
		(sum(ts.SUB_TOTAL_AMT)-sum(ts.TOTAL_AMT)) AS REWARE,
		'''' AS QTY_S ,
		'''' AS UNIT_T,
		'''' AS TARGETS
 FROM TS_SALE_ITEM ts


    WHERE COMMON_TRN_NO in ( '+@COMMON_TRN_NO +') AND POS_NO ='+CAST(@POS_NO AS CHAR)+' group by ts.RECEIPT_NO,ts.POS_NO
 UNION ALL
SELECT  '''' AS RECEIPT,
		'''' AS POS,
		ts.PRODUCT_CODE,
		ts.PRODUCT_NAME,
		CAST(ts.UNIT_PRICE AS CHAR) AS PRICE,
		CAST(SUM(ts.QTY)AS CHAR) AS QTY,
		SUM(ts.SUB_TOTAL_AMT) AS TOTAL_AMT ,
		SUM(ts.SUB_TOTAL_AMT)-SUM(ts.TOTAL_AMT) AS REWARE_VALUE,
		ISNULL(CAST(ms.QTY_SOURCE AS CHAR),'''') AS QTY_S,
		ISNULL(ms.UNIT_TYPE_SOURCE,''''),
		ISNULL(ms.PRODUCT_TARGET,'''')
 FROM TS_SALE_ITEM ts LEFT jOIN MS_PRODUCT_CONVERT ms ON ts.PRODUCT_CODE = ms.PRODUCT_SOURCE
   WHERE COMMON_TRN_NO in ( '+@COMMON_TRN_NO +')AND POS_NO ='+CAST(@POS_NO AS CHAR)+' GROUP BY PRODUCT_CODE,PRODUCT_NAME,UNIT_PRICE,SUB_TOTAL_AMT,TOTAL_AMT,QTY_SOURCE,UNIT_TYPE_SOURCE,PRODUCT_TARGET ORDER BY PRODUCT_CODE '
DECLARE @SQL NVARCHAR(MAX) = 'SELECT
    COALESCE(HITRULE.RECEIPT_NO, '''') AS RCNO,
    COALESCE(HITRULE.POS_NO, '''') AS NO,
    COALESCE(ITEM.RULE_ID, '''') AS RULE_ID,
    HEADER.PROM_DESC,
    COALESCE(ITEM.REWARD_NAME, '''') AS RULE_NAME,

    COALESCE(CAST(ROUND(ITEM.DISCOUNT_AMT, 0) AS INT), 0) AS UNIT,
	COALESCE(''ชิ้น'', '''') AS UNITRU,
    COALESCE(CAST(SUM(ITEM.QTY) AS FLOAT), 0) AS PRICE,
	COALESCE(''บาท'', '''') AS UNIT,
    COALESCE(SUM(CASE
        WHEN ISNUMERIC(ITEM.DISCOUNT_AMT) = 1 THEN CAST(ITEM.DISCOUNT_AMT AS DECIMAL(10, 2))
        ELSE 0 END), 0 ) AS SUMAMT,
	COALESCE(''บาท'', '''') AS UNITAMT ,
	CASE
		WHEN HITRULE.PROMOTION_TYPE = 3 THEN ''เเจก''
		WHEN HITRULE.PROMOTION_TYPE = 1 THEN ''ใช้''
		ELSE ''NOTYPE''
	END AS TYPE,
	HEADER.MMBR_ACCT_ID AS MMBR_ID,HEADER.RWRD_MMBR_ACCOUNT AS RWRD_MMBR

FROM TA_PROMOTION_ITEM AS ITEM
LEFT JOIN TA_PROMOTION_HITRULE AS HITRULE
    ON ITEM.RULE_ID = HITRULE.RULE_ID
LEFT JOIN LPE_PROM.dbo.LPE_PromotionHeader  AS HEADER
	ON HITRULE.RULE_ID = HEADER.MMBR_PROM_ID
WHERE ITEM.COMMON_TRN_NO = @COMMON_TRN_NO
    AND HITRULE.COMMON_TRN_NO in ( @COMMON_TRN_NO ) AND HITRULE.POS_NO = @POS_NO
GROUP BY HITRULE.RECEIPT_NO, ITEM.RULE_ID, ITEM.REWARD_NAME, ITEM.DISCOUNT_AMT,HITRULE.POS_NO,HITRULE.PROMOTION_TYPE,HEADER.MMBR_ACCT_ID,HEADER.RWRD_MMBR_ACCOUNT ,HEADER.PROM_DESC

UNION ALL
SELECT     COALESCE(HITRULE.RECEIPT_NO, '''') AS RCNO,
    COALESCE(HITRULE.POS_NO, '''') AS NO,
    COALESCE(COUPON.RULE_ID, '''') AS RULE_ID,
    HEADER.PROM_DESC,
    COALESCE(HITRULE.RULE_NAME, '''') AS RULE_NAME,
	COALESCE(CAST(ROUND(SUM(COUPON.PRODUCT_SEQ_NO), 0) AS INT), 0) AS UNIT,

	COALESCE(''ชิ้น'', '''') AS UNITRU,
    COALESCE(ROUND(COUNT(*), 0), 0) AS PRICE,
	COALESCE(''บาท'', '''') AS UNIT,
	COALESCE(ROUND(CAST(CASE
        WHEN COUNT(COUPON.DISCOUNT_AMT) = 0 THEN 0
        ELSE COUNT(COUPON.DISCOUNT_AMT) * SUM(COUPON.PRODUCT_SEQ_NO)
    END AS FLOAT), 2), 0 ) AS SUMAMT,
	COALESCE(''บาท'', '''') AS UNITAMT ,
	CASE
		WHEN HITRULE.PROMOTION_TYPE = 3 THEN ''เเจก''
		WHEN HITRULE.PROMOTION_TYPE = 1 THEN ''ใช้''
		ELSE ''NOTYPE''
	END AS TYPE,
	HEADER.MMBR_ACCT_ID AS MMBR_ID,HEADER.RWRD_MMBR_ACCOUNT AS RWRD_MMBR

  FROM TA_PROMOTION_COUPON as COUPON LEFT JOIN TA_PROMOTION_HITRULE AS HITRULE
    ON COUPON.RULE_ID = HITRULE.RULE_ID AND COUPON.COMMON_TRN_NO =HITRULE.COMMON_TRN_NO
  	LEFT JOIN LPE_PROM.dbo.LPE_PromotionHeader  AS HEADER
	ON HITRULE.RULE_ID = HEADER.MMBR_PROM_ID
	where COUPON.COMMON_TRN_NO  in ( @COMMON_TRN_NO )  AND HITRULE.POS_NO = @POS_NO
	GROUP BY HITRULE.RECEIPT_NO,HITRULE.POS_NO,COUPON.RULE_ID,HITRULE.RULE_NAME,HITRULE.PROMOTION_TYPE,HEADER.MMBR_ACCT_ID,HEADER.RWRD_MMBR_ACCOUNT ,HEADER.PROM_DESC

UNION  ALL

SELECT
    COALESCE(HITRULE.RECEIPT_NO, '''') AS RCNO,
    COALESCE(HITRULE.POS_NO, '''') AS NO,
    COALESCE(POINT.CAMPAIGN_ID, '''') AS RULE_ID,
    HEADER.PROM_DESC,
    COALESCE(HITRULE.RULE_NAME, '''') AS RULE_NAME,

    COALESCE(CAST(ROUND(COUNT(*), 0) AS INT), 0) AS UNIT,
	COALESCE(''ชิ้น'', '''') AS UNITRU,
    COALESCE(ROUND(COUNT(*), 0), 0) AS PRICE,
	COALESCE(''บาท'', '''') AS UNIT,
    COALESCE(ROUND(CAST(CASE
        WHEN COUNT(POINT.QTY) = 0 THEN 0
        ELSE SUM(POINT.QTY) / COUNT(POINT.QTY)
    END AS FLOAT), 2), 0 ) AS SUMAMT,
	COALESCE(''บาท'', '''') AS UNITAMT ,
	CASE
		WHEN HITRULE.PROMOTION_TYPE = 3 THEN ''เเจก''
		WHEN HITRULE.PROMOTION_TYPE = 1 THEN ''ใช้''
		ELSE ''NOTYPE''
	END AS TYPE,
	HEADER.MMBR_ACCT_ID AS MMBR_ID,HEADER.RWRD_MMBR_ACCOUNT AS RWRD_MMBR

FROM TA_PROMOTION_POINT AS POINT
LEFT JOIN TA_PROMOTION_HITRULE AS HITRULE
    ON POINT.CAMPAIGN_ID = HITRULE.RULE_ID
LEFT JOIN LPE_PROM.dbo.LPE_PromotionHeader  AS HEADER
	ON HITRULE.RULE_ID = HEADER.MMBR_PROM_ID
WHERE POINT.POINT_ID IN (''808'', ''00000000'')
    AND HITRULE.COMMON_TRN_NO in ( @COMMON_TRN_NO )  AND HITRULE.POS_NO = @POS_NO
GROUP BY POINT.CAMPAIGN_ID, HITRULE.RULE_ID, HITRULE.RULE_NAME, HITRULE.RECEIPT_NO,HITRULE.POS_NO,HITRULE.PROMOTION_TYPE,HEADER.MMBR_ACCT_ID,HEADER.RWRD_MMBR_ACCOUNT ,HEADER.PROM_DESC



UNION ALL
SELECT
    COALESCE(HITRULE.RECEIPT_NO, '''') AS RCNO,
    COALESCE(HITRULE.POS_NO, '''') AS NO,
    COALESCE(HITRULE.RULE_ID, '''') AS RULE_ID,
    HEADER.PROM_DESC,
    COALESCE(PREMIUM.PREMIUM_NAME, '''') AS RULE_NAME,

    COALESCE(CAST(ROUND(CASE WHEN PREMIUM.PREMIUM_ID = @Mstamp_3 THEN 3 ELSE 1 END,0) AS INT), 0) AS UNIT,
	COALESCE(''ดวง'', '''') AS UNITRU,
    CAST(ROUND(SUM(PREMIUM.QTY), 0) AS FLOAT) AS PRICE,
	COALESCE(CASE WHEN PREMIUM.PREMIUM_ID != @Mstamp_3 AND PREMIUM.PREMIUM_ID != @Mstamp_1 THEN ''สิทธิ์'' ELSE ''หน่วย'' END,'''') AS UNIT,
    CAST(ROUND(SUM(CASE WHEN PREMIUM.PREMIUM_ID = @Mstamp_3 THEN PREMIUM.QTY * 3 ELSE QTY END), 0) AS INT ) AS SUMAMT,
	COALESCE(CASE WHEN PREMIUM.PREMIUM_ID != @Mstamp_3 AND PREMIUM.PREMIUM_ID != @Mstamp_1 THEN ''สิทธิ์'' ELSE ''บาท''END,'''') AS UNITAMT ,
	CASE
		WHEN HITRULE.PROMOTION_TYPE = 3 THEN ''เเจก''
		WHEN HITRULE.PROMOTION_TYPE = 1 THEN ''ใช้''
		ELSE ''NOTYPE''
	END AS TYPE,
	HEADER.MMBR_ACCT_ID AS MMBR_ID,HEADER.RWRD_MMBR_ACCOUNT AS RWRD_MMBR

FROM TA_PROMOTION_PREMIUM AS PREMIUM
INNER JOIN TA_PROMOTION_HITRULE AS HITRULE
    ON HITRULE.COMMON_TRN_NO = PREMIUM.COMMON_TRN_NO
    AND HITRULE.POS_NO = PREMIUM.POS_NO
	AND HITRULE.RULE_ID = PREMIUM.RULE_ID
LEFT JOIN LPE_PROM.dbo.LPE_PromotionHeader  AS HEADER
	ON HITRULE.RULE_ID = HEADER.MMBR_PROM_ID
WHERE PREMIUM.PREMIUM_ID  !=''''
    AND PREMIUM.COMMON_TRN_NO in ( @COMMON_TRN_NO )
    AND PREMIUM.POS_NO = @POS_NO
GROUP BY PREMIUM.PREMIUM_NAME, PREMIUM.COMMON_TRN_NO, HITRULE.RECEIPT_NO, HITRULE.RULE_ID, PREMIUM.PREMIUM_ID,HITRULE.POS_NO ,HITRULE.PROMOTION_TYPE,HEADER.MMBR_ACCT_ID,HEADER.RWRD_MMBR_ACCOUNT ,HEADER.PROM_DESC

UNION ALL
SELECT
    COALESCE(RECEIPT_NO, '''') AS RCNO,
    COALESCE(POS_NO, '''') AS NO,
    COALESCE(RULE_ID, '''') AS RULE_ID,
    HEADER.PROM_DESC,
    COALESCE(RULE_NAME, '''') AS RULE_NAME,

    COALESCE(CAST(ROUND(0, 0) AS INT), 0) AS UNIT,
	COALESCE(''SLIPAD'', '''') AS UNITRU,
    COALESCE(ROUND(0, 0), 0) AS PRICE,
	COALESCE(''SLIPAD'', '''') AS UNIT,
    COALESCE(ROUND(0, 0), 0 ) AS SUMAMT,
	COALESCE(''-'', '''') AS UNITAMT ,
	CASE
		WHEN PROMOTION_TYPE = 3 THEN ''เเจก''
		WHEN PROMOTION_TYPE = 1 THEN ''ใช้''
		ELSE ''NOTYPE''
	END AS TYPE,
	HEADER.MMBR_ACCT_ID AS MMBR_ID,HEADER.RWRD_MMBR_ACCOUNT AS RWRD_MMBR

FROM #TempTable
	LEFT JOIN LPE_PROM.dbo.LPE_PromotionHeader  AS HEADER
	ON RULE_ID = HEADER.MMBR_PROM_ID
WHERE NOT (RULE_ID IN (SELECT RULE_ID
                        FROM TA_PROMOTION_PREMIUM
                        WHERE COMMON_TRN_NO in ( @COMMON_TRN_NO )
                        AND POS_NO = @POS_NO)
           OR RULE_ID IN (SELECT RULE_ID
                          FROM TA_PROMOTION_POINT
                          WHERE COMMON_TRN_NO in ( @COMMON_TRN_NO )
                          AND POS_NO = @POS_NO)

			OR RULE_ID IN (SELECT RULE_ID
                          FROM TA_PROMOTION_COUPON
                          WHERE COMMON_TRN_NO in ( @COMMON_TRN_NO )
                          AND POS_NO = @POS_NO)
			OR RULE_ID IN (SELECT RULE_ID
                          FROM TA_PROMOTION_ITEM
                          WHERE COMMON_TRN_NO in ( @COMMON_TRN_NO )
                          AND POS_NO = @POS_NO))AND POS_NO = @POS_NO
GROUP BY RECEIPT_NO, RULE_ID, RULE_NAME,POS_NO,PROMOTION_TYPE,HEADER.MMBR_ACCT_ID,HEADER.RWRD_MMBR_ACCOUNT ,HEADER.PROM_DESC;
';
-- รันคำสั่ง SQL

IF LEN(@PromotionCode) > 1 or LEN(@ProductCode) > 1
BEGIN
	EXEC sp_executesql @SqlCount;
	EXEC sp_executesql @SqlPromotion;
END
DECLARE @PARAMS NVARCHAR(MAX);
SET @PARAMS = N'@COMMON_TRN_NO NVARCHAR(50), @POS_NO INT, @Mstamp_3 NVARCHAR(50), @Mstamp_1 NVARCHAR(50), @PREMIUM_ID NVARCHAR(50)';

EXEC sp_executesql @SQL, @PARAMS,
     @COMMON_TRN_NO ,
     @POS_NO ,
     @Mstamp_3 ,
	 @Mstamp_1 ,
     @PREMIUM_ID ;
EXEC sp_executesql @ITEM
